title: The Kovri I2P Router Project
description: Kovri, a secure, private, untraceable C++ router implementation of I2P
baseurl: ""
permalink: /:title/
exclude: [".gitignore", "README.md"]
# Plugins
plugins_dir: 
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

# Gems
gems: [jekyll-paginate, jekyll-multiple-languages-plugin]

# paginate
paginate: 10
paginate_path: blog/page:num/

# jekyll-multiple-languages-plugin settings:
languages: ["en", "es", "ru", "fr", "it", "de", "da"]

exclude_from_localizations: ["img", "css", "fonts", "Kovri Website Instructions.md", "_posts", "doxygen", "doxygen.html"]
